<?xml version="1.0"?>

<robot name="quad_tilt_wing" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="fuselage_length" value="1"/>
  <xacro:property name="fuselage_height" value="0.05"/>
  <xacro:property name="wing_rod_radius" value="0.01"/>
  <xacro:property name="wing_rod_length_front" value="0.3"/>
  <xacro:property name="wing_rod_length_rear" value="0.5"/>
  <xacro:property name="wing_wing_thickness" value="${wing_rod_radius*2}"/>
  <xacro:property name="wing_wing_length_front" value="${wing_rod_length_front-0.1}"/>
  <xacro:property name="wing_wing_length_rear" value="${wing_rod_length_rear-0.1}"/>
  <xacro:property name="wing_wing_width" value="0.2"/>
  <xacro:property name="prop_disk_radius" value="0.1"/>
  <xacro:property name="prop_disk_thickness" value="0.01"/>
  <xacro:property name="front_wing_joint" value="0.4"/>
  <xacro:property name="rear_wing_joint" value="-0.1"/>
  <xacro:property name="motor_radius" value="0.01"/>
  <xacro:property name="motor_length" value="0.03"/>
<!--
  <xacro:property name="pi" value="3.1415926"/>
-->
  
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="blue_trans">
    <color rgba="0 0 0.8 0.5"/>
  </material>
  

  <link name="fuselage">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${fuselage_length} ${fuselage_height} ${fuselage_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  
  <link name="top_indicator">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${fuselage_length/2} ${fuselage_height} ${fuselage_height/2}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
  
  <joint name="top_to_fuselage" type="fixed">
    <parent link="fuselage"/>
    <child link="top_indicator"/>
    <origin xyz="${fuselage_length/4} 0 ${fuselage_height/4*3}"/>
  </joint>
  
  <link name="wing_1_rod">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${wing_rod_length_front}" radius="${wing_rod_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 ${wing_rod_length_front/2} 0"/>
      <material name="white"/>
    </visual>
  </link>
  
  <joint name="wing_1_joint" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-${2/3*pi}" upper="${pi/6}" velocity="0.5"/>
    <parent link="fuselage"/>
    <child link="wing_1_rod"/>
    <origin xyz="${front_wing_joint} 0 0"/>
  </joint>
  
  <link name="wing_1_wing">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${wing_wing_width} ${wing_wing_length_front} ${wing_wing_thickness}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-${wing_wing_width/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  
  <joint name="wing_1_wing_to_rod" type="fixed">
    <parent link="wing_1_rod"/>
    <child link="wing_1_wing"/>
    <origin xyz="0 ${wing_rod_length_front/2} 0"/>
  </joint>
  
  <link name="wing_1_motor">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${motor_length}" radius="${motor_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${motor_length/2} 0 0"/>
      <material name="black"/>
    </visual>
  </link>
  
  <joint name="wing_1_motor_to_rod" type="fixed">
    <parent link="wing_1_rod"/>
    <child link="wing_1_motor"/>
    <origin xyz="0 ${wing_rod_length_front/2} 0"/>
  </joint>
  
  <link name="wing_1_prop">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${prop_disk_thickness}" radius="${prop_disk_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${prop_disk_thickness/2} 0 0"/>
      <material name="blue_trans"/>
    </visual>
  </link>
  
  <joint name="wing_1_prop_to_motor" type="fixed">
    <parent link="wing_1_motor"/>
    <child link="wing_1_prop"/>
    <origin xyz="${motor_length} 0 0"/>
  </joint>
  
  <link name="wing_2_rod">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${wing_rod_length_front}" radius="${wing_rod_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 -${wing_rod_length_front/2} 0"/>
      <material name="white"/>
    </visual>
  </link>
  
  <joint name="wing_2_joint" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-${2/3*pi}" upper="${pi/6}" velocity="0.5"/>
    <parent link="fuselage"/>
    <child link="wing_2_rod"/>
    <origin xyz="${front_wing_joint} 0 0"/>
  </joint>
  
  <link name="wing_2_wing">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${wing_wing_width} ${wing_wing_length_front} ${wing_wing_thickness}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-${wing_wing_width/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  
  <joint name="wing_2_wing_to_rod" type="fixed">
    <parent link="wing_2_rod"/>
    <child link="wing_2_wing"/>
    <origin xyz="0 -${wing_rod_length_front/2} 0"/>
  </joint>
  
  <link name="wing_2_motor">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${motor_length}" radius="${motor_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${motor_length/2} 0 0"/>
      <material name="black"/>
    </visual>
  </link>
  
  <joint name="wing_2_motor_to_rod" type="fixed">
    <parent link="wing_2_rod"/>
    <child link="wing_2_motor"/>
    <origin xyz="0 -${wing_rod_length_front/2} 0"/>
  </joint>
  
  <link name="wing_2_prop">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${prop_disk_thickness}" radius="${prop_disk_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${prop_disk_thickness/2} 0 0"/>
      <material name="blue_trans"/>
    </visual>
  </link>
  
  <joint name="wing_2_prop_to_motor" type="fixed">
    <parent link="wing_2_motor"/>
    <child link="wing_2_prop"/>
    <origin xyz="${motor_length} 0 0"/>
  </joint>
  
  <link name="wing_3_rod">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${wing_rod_length_rear}" radius="${wing_rod_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 ${wing_rod_length_rear/2} 0"/>
      <material name="white"/>
    </visual>
  </link>
  
  <joint name="wing_3_joint" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-${2/3*pi}" upper="${pi/6}" velocity="0.5"/>
    <parent link="fuselage"/>
    <child link="wing_3_rod"/>
    <origin xyz="${rear_wing_joint} 0 0"/>
  </joint>
  
  <link name="wing_3_wing">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${wing_wing_width} ${wing_wing_length_rear} ${wing_wing_thickness}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-${wing_wing_width/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  
  <joint name="wing_3_wing_to_rod" type="fixed">
    <parent link="wing_3_rod"/>
    <child link="wing_3_wing"/>
    <origin xyz="0 ${wing_rod_length_rear/2} 0"/>
  </joint>
  
  <link name="wing_3_motor">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${motor_length}" radius="${motor_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${motor_length/2} 0 0"/>
      <material name="black"/>
    </visual>
  </link>
  
  <joint name="wing_3_motor_to_rod" type="fixed">
    <parent link="wing_3_rod"/>
    <child link="wing_3_motor"/>
    <origin xyz="0 ${wing_rod_length_rear/2} 0"/>
  </joint>
  
  <link name="wing_3_prop">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${prop_disk_thickness}" radius="${prop_disk_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${prop_disk_thickness/2} 0 0"/>
      <material name="blue_trans"/>
    </visual>
  </link>
  
  <joint name="wing_3_prop_to_motor" type="fixed">
    <parent link="wing_3_motor"/>
    <child link="wing_3_prop"/>
    <origin xyz="${motor_length} 0 0"/>
  </joint>
  
  <link name="wing_4_rod">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${wing_rod_length_rear}" radius="${wing_rod_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0" xyz="0 -${wing_rod_length_rear/2} 0"/>
      <material name="white"/>
    </visual>
  </link>
  
  <joint name="wing_4_joint" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="-${2/3*pi}" upper="${pi/6}" velocity="0.5"/>
    <parent link="fuselage"/>
    <child link="wing_4_rod"/>
    <origin xyz="${rear_wing_joint} 0 0"/>
  </joint>
  
  <link name="wing_4_wing">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${wing_wing_width} ${wing_wing_length_rear} ${wing_wing_thickness}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-${wing_wing_width/2} 0 0"/>
      <material name="blue"/>
    </visual>
  </link>
  
  <joint name="wing_4_wing_to_rod" type="fixed">
    <parent link="wing_4_rod"/>
    <child link="wing_4_wing"/>
    <origin xyz="0 -${wing_rod_length_rear/2} 0"/>
  </joint>
  
  <link name="wing_4_motor">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${motor_length}" radius="${motor_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${motor_length/2} 0 0"/>
      <material name="black"/>
    </visual>
  </link>
  
  <joint name="wing_4_motor_to_rod" type="fixed">
    <parent link="wing_4_rod"/>
    <child link="wing_4_motor"/>
    <origin xyz="0 -${wing_rod_length_rear/2} 0"/>
  </joint>
  
  <link name="wing_4_prop">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="${prop_disk_thickness}" radius="${prop_disk_radius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} 0" xyz="${prop_disk_thickness/2} 0 0"/>
      <material name="blue_trans"/>
    </visual>
  </link>
  
  <joint name="wing_4_prop_to_motor" type="fixed">
    <parent link="wing_4_motor"/>
    <child link="wing_4_prop"/>
    <origin xyz="${motor_length} 0 0"/>
  </joint>
  
  


</robot>
